<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/4_Problems/2_04_Pandas Pivot Tables.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [1]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

data_jobs.csv:   0%|          | 0.00/231M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

## 🟩 Count Job Postings by Title and Country (2.4.1)

In [15]:
df_job_title_country = df.pivot_table(
    index='job_title_short',
    columns='job_country',
    aggfunc='size', #counting
    fill_value=0 #replace NaN with 0
)
df_job_title_country

job_country,Afghanistan,Albania,Algeria,Angola,Argentina,Armenia,Australia,Austria,Azerbaijan,Bahamas,...,United Arab Emirates,United Kingdom,United States,Uruguay,Uzbekistan,Venezuela,Vietnam,Yemen,Zambia,Zimbabwe
job_title_short,,,,,,,,,,,,,,,,,,,,,
Business Analyst,4,11,21,1,453,29,928,738,16,5,...,984,827,7382,199,55,2,91,3,30,6
Cloud Engineer,0,1,5,0,322,4,489,266,0,2,...,93,193,423,53,3,2,70,0,4,3
Data Analyst,9,36,22,2,1273,33,1658,2169,21,7,...,2587,10482,67816,227,39,16,334,4,40,34
Data Engineer,0,30,21,3,2265,45,4658,2175,7,14,...,1139,11807,35080,248,49,19,768,2,5,11
Data Scientist,1,12,27,1,1617,28,1179,1709,16,5,...,1360,9148,58830,140,50,9,375,0,13,13
Machine Learning Engineer,0,4,2,0,287,22,360,305,2,3,...,164,317,921,46,22,4,115,0,2,1
Senior Data Analyst,2,2,0,0,255,22,310,301,2,1,...,262,1356,11791,50,15,4,71,0,5,1
Senior Data Engineer,0,6,1,0,647,57,1482,542,4,12,...,227,3337,9289,106,54,4,220,0,0,3
Senior Data Scientist,0,11,0,1,350,16,302,451,1,1,...,245,2367,12946,54,19,3,91,0,2,1
Software Engineer,0,6,12,3,1267,33,1589,1054,14,19,...,480,541,1814,263,27,6,279,1,3,8

---

## 🟨 Salary Stats by Job Title (2.4.2)

In [16]:
salary_stats = df.pivot_table(
    index='job_title_short',
    values='salary_year_avg',
    aggfunc=['mean', 'median', 'min', 'max', 'count']
)

salary_stats

,mean,median,min,max,count
,salary_year_avg,salary_year_avg,salary_year_avg,salary_year_avg,salary_year_avg
job_title_short,,,,,
Business Analyst,91082.612833,85000.0,16500.0,387460.0,610
Cloud Engineer,111268.453846,90000.0,42000.0,280000.0,65
Data Analyst,93841.907854,90000.0,25000.0,650000.0,5451
Data Engineer,130125.604250,125000.0,15000.0,525000.0,4500
Data Scientist,135988.837171,127500.0,27000.0,960000.0,5922
Machine Learning Engineer,126774.315972,106415.0,30000.0,325000.0,576
Senior Data Analyst,113911.363665,111175.0,30000.0,425000.0,1131
Senior Data Engineer,145840.611624,147500.0,35000.0,425000.0,1591
Senior Data Scientist,154206.292996,155500.0,45000.0,890000.0,1690
Software Engineer,113393.760054,99150.0,28000.0,375000.0,467

---

## 🟥 Sum Salary by Title and Country (2.4.3)

In [17]:
salary_sum = df.pivot_table(
    index='job_title_short',
    columns='job_country',
    values='salary_year_avg',
    aggfunc='sum',
    fill_value=0
)

salary_sum

job_country,Afghanistan,Albania,Algeria,Angola,Argentina,Armenia,Australia,Austria,Azerbaijan,Bahamas,...,United Arab Emirates,United Kingdom,United States,Uruguay,Uzbekistan,Venezuela,Vietnam,Yemen,Zambia,Zimbabwe
job_title_short,,,,,,,,,,,,,,,,,,,,,
Business Analyst,0.0,0.0,0.0,0.0,142200.0,0.0,263000.0,0.0,0.0,0.0,...,0.0,247800.0,4.145162e+07,0.0,0.0,0.0,223200.0,0.0,0.0,0.0
Cloud Engineer,0.0,0.0,0.0,0.0,197500.0,0.0,110000.0,0.0,0.0,0.0,...,0.0,0.0,2.401818e+06,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Data Analyst,0.0,99900.0,44100.0,0.0,341745.5,201000.0,411500.0,378496.0,0.0,0.0,...,459375.0,6437586.0,4.113097e+08,100500.0,0.0,0.0,999267.0,0.0,0.0,63000.0
Data Engineer,0.0,0.0,45000.0,0.0,1225599.0,97500.0,3374399.5,405000.0,0.0,1755244.0,...,752992.5,6937332.0,3.912708e+08,0.0,0.0,0.0,1576131.0,0.0,0.0,0.0
Data Scientist,0.0,139962.5,0.0,0.0,597221.5,0.0,978291.0,142499.5,0.0,0.0,...,166419.5,8268820.0,6.371774e+08,0.0,30750.0,0.0,534400.0,0.0,90670.0,138170.0
Machine Learning Engineer,0.0,0.0,0.0,0.0,393029.0,174042.0,856129.0,178200.0,0.0,457500.0,...,125700.0,976951.0,1.974277e+07,50000.0,0.0,0.0,571050.0,0.0,0.0,0.0
Senior Data Analyst,0.0,0.0,0.0,0.0,0.0,0.0,101280.0,178200.0,0.0,0.0,...,421350.0,858515.0,1.056607e+08,0.0,0.0,0.0,402050.0,0.0,0.0,0.0
Senior Data Engineer,0.0,0.0,0.0,0.0,295000.0,0.0,1079046.0,531600.0,0.0,1287500.0,...,0.0,3301200.5,1.602320e+08,0.0,0.0,0.0,508500.0,0.0,0.0,0.0
Senior Data Scientist,0.0,157500.0,0.0,0.0,0.0,0.0,787500.0,80850.0,0.0,0.0,...,216000.0,4011376.0,1.977291e+08,57500.0,0.0,0.0,79200.0,0.0,0.0,0.0
Software Engineer,0.0,0.0,0.0,0.0,174500.0,0.0,843935.0,0.0,72000.0,731500.0,...,79200.0,516400.0,2.166049e+07,0.0,0.0,0.0,107200.0,0.0,0.0,0.0

---